version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.0-alpine
    env_file:
      - ./backend/.env.postgres
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/
    depends_on:
      - api

volumes:
  backend_postgres_data:
