version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - backend:/usr/src/app
      - static:/src/app/static
      - media:/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db-service
    image: sebastian677/django-react-craftech:back_latest

  db-service:
    container_name: db-service
    image: postgres:12.0-alpine
    env_file:
      - ./backend/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  react:
    container_name: react
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend_app:/usr/src/app/
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
    image: sebastian677/django-react-craftech:front_latest

volumes:
  backend:
  static:
  media:
  postgres_data:
  frontend_app:
