apiVersion: v1
kind: Pod
metadata:
  name: django-api
  labels:
    app: django-api
spec:
  containers:
    - name: api
      image: sebastian677/django-react-craftech:back_latest
      env:
        - name: SQL_ENGINE #kubectl create configmap backend-config --from-env-file=config.env
          value: "django.db.backends.postgresql"
        - name: SQL_DATABASE
          value: "core"
        - name: SQL_USER
          value: "user"
        - name: SQL_PASSWORD
          value: "password"
        - name: SQL_HOST
          value: "db-service"
        - name: SQL_PORT
          value: "5432"
      volumeMounts:
        - name: backend
          mountPath: /usr/src/app
        - name: static
          mountPath: /src/app/static
        - name: media
          mountPath: /src/app/media
      ports:
        - containerPort: 8000
  volumes:
    - name: backend
      emptyDir: {}
    - name: static
      emptyDir: {}
    - name: media
      emptyDir: {}

---

apiVersion: v1
kind: Pod
metadata:
  name: react-frontend
  labels:
    app: react-frontend
spec:
  containers:
    - name: react
      image: sebastian677/django-react-craftech:front_latest
      env:
        - name: CHOKIDAR_USEPOLLING
          value: "true"
      volumeMounts:
        - name: frontend-app
          mountPath: /usr/src/app
      ports:
        - containerPort: 3000
  volumes:
    - name: frontend-app
      emptyDir: {}
