apiVersion: v1
kind: Pod
metadata:
  name: django-api
  labels:
    app: django-api
spec:
  containers:
    - name: api
      image: sebastian677/django-react-craftech:back_latest
      envFrom:
        - configMapRef:
            name: back-config
      volumeMounts:
        - name: backend
          mountPath: /usr/src/app
        - name: static
          mountPath: /src/app/static
        - name: media
          mountPath: /src/app/media
      ports:
        - containerPort: 8000
  volumes:
    - name: backend
      emptyDir: {}
    - name: static
      emptyDir: {}
    - name: media
      emptyDir: {}

---

apiVersion: v1
kind: Pod
metadata:
  name: react-frontend
  labels:
    app: react-frontend
spec:
  containers:
    - name: react
      image: sebastian677/django-react-craftech:front_latest
      envFrom:
        - configMapRef:
            name: front-config
      volumeMounts:
        - name: frontend-app
          mountPath: /usr/src/app
      ports:
        - containerPort: 3000
  volumes:
    - name: frontend-app
      emptyDir: {}
