apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  #loadBalancerIP: 10.10.10.10
  selector:
    app: react-frontend # este es el pod  al que se mapea el servicio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: django-api-service
spec:
  type: LoadBalancer
  selector:
    app: django-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 30080 
