name: CI Pipeline

on:
  push:
    paths:
      - 'Challenge3/Nginx/index.html'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker-compose -f Challenge3/docker-compose.yml build

      - name: Tag Docker image
        run: |
          IMAGE_NAME=challenge1/nginx-indexTest
          IMAGE_TAG=latest
          docker tag Challenge3_image_name:latest $IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker image
        run: |
          IMAGE_NAME=challenge1/nginx-indexTest
          IMAGE_TAG=latest
          docker push $IMAGE_NAME:$IMAGE_TAG

